-- Create lms_certificates table with updated structure
CREATE TABLE IF NOT EXISTS `lms_certificates` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `course_id` bigint(20) unsigned NOT NULL COMMENT 'ID kursus',
  `enrollment_id` bigint(20) unsigned NULL COMMENT 'ID enrollment (nullable)',
  `user_id` bigint(20) unsigned NOT NULL COMMENT 'ID user',
  `certificate_number` varchar(100) NOT NULL COMMENT 'Nomor sertifikat',
  `issued_at` timestamp NULL DEFAULT NULL COMMENT 'Tanggal terbit',
  `expires_at` timestamp NULL DEFAULT NULL COMMENT 'Tanggal kadaluarsa',
  `template_id` bigint(20) unsigned NULL COMMENT 'ID template sertifikat',
  `status` enum('active','expired','revoked') DEFAULT 'active' COMMENT 'Status sertifikat',
  `created_by` bigint(20) unsigned NULL COMMENT 'User yang membuat',
  `updated_by` bigint(20) unsigned NULL COMMENT 'User yang mengupdate',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `lms_certificates_certificate_number_unique` (`certificate_number`),
  KEY `lms_certificates_course_id_foreign` (`course_id`),
  KEY `lms_certificates_enrollment_id_foreign` (`enrollment_id`),
  KEY `lms_certificates_user_id_foreign` (`user_id`),
  KEY `lms_certificates_template_id_foreign` (`template_id`),
  KEY `lms_certificates_created_by_foreign` (`created_by`),
  KEY `lms_certificates_updated_by_foreign` (`updated_by`),
  KEY `lms_certificates_status_index` (`status`),
  KEY `lms_certificates_deleted_at_index` (`deleted_at`),
  CONSTRAINT `lms_certificates_course_id_foreign` FOREIGN KEY (`course_id`) REFERENCES `lms_courses` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lms_certificates_enrollment_id_foreign` FOREIGN KEY (`enrollment_id`) REFERENCES `lms_enrollments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `lms_certificates_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lms_certificates_template_id_foreign` FOREIGN KEY (`template_id`) REFERENCES `certificate_templates` (`id`) ON DELETE SET NULL,
  CONSTRAINT `lms_certificates_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `lms_certificates_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sertifikat kelulusan';
