CREATE TABLE IF NOT EXISTS `approval_requests` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL COMMENT 'User yang mengajukan izin',
  `approver_id` bigint(20) unsigned NOT NULL COMMENT 'User yang harus approve (atasan)',
  `leave_type_id` bigint(20) unsigned NOT NULL COMMENT 'Jenis izin/cuti',
  `date_from` date NOT NULL COMMENT 'Tanggal mulai izin',
  `date_to` date NOT NULL COMMENT 'Tanggal selesai izin',
  `reason` text NOT NULL COMMENT 'Alasan izin',
  `document_path` varchar(255) NULL DEFAULT NULL COMMENT 'Path dokumen pendukung',
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending' COMMENT 'Status approval',
  `approved_at` timestamp NULL DEFAULT NULL COMMENT 'Waktu approval',
  `rejected_at` timestamp NULL DEFAULT NULL COMMENT 'Waktu rejection',
  `approval_notes` text NULL DEFAULT NULL COMMENT 'Catatan dari approver',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `approval_requests_user_id_foreign` (`user_id`),
  KEY `approval_requests_approver_id_foreign` (`approver_id`),
  KEY `approval_requests_leave_type_id_foreign` (`leave_type_id`),
  KEY `approval_requests_status_index` (`status`),
  KEY `approval_requests_created_at_index` (`created_at`),
  CONSTRAINT `approval_requests_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `approval_requests_approver_id_foreign` FOREIGN KEY (`approver_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `approval_requests_leave_type_id_foreign` FOREIGN KEY (`leave_type_id`) REFERENCES `leave_types` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
