CREATE TABLE `outlet_wip_productions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `production_date` date NOT NULL,
  `batch_number` varchar(255) DEFAULT NULL,
  `item_id` bigint(20) unsigned NOT NULL,
  `qty` decimal(10,2) NOT NULL,
  `qty_jadi` decimal(10,2) NOT NULL,
  `unit_id` bigint(20) unsigned NOT NULL,
  `outlet_id` bigint(20) unsigned NOT NULL,
  `warehouse_outlet_id` bigint(20) unsigned NOT NULL,
  `notes` text DEFAULT NULL,
  `created_by` bigint(20) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `outlet_wip_productions_item_id_foreign` (`item_id`),
  KEY `outlet_wip_productions_unit_id_foreign` (`unit_id`),
  KEY `outlet_wip_productions_outlet_id_foreign` (`outlet_id`),
  KEY `outlet_wip_productions_warehouse_outlet_id_foreign` (`warehouse_outlet_id`),
  KEY `outlet_wip_productions_created_by_foreign` (`created_by`),
  CONSTRAINT `outlet_wip_productions_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `outlet_wip_productions_item_id_foreign` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `outlet_wip_productions_outlet_id_foreign` FOREIGN KEY (`outlet_id`) REFERENCES `tbl_data_outlet` (`id_outlet`),
  CONSTRAINT `outlet_wip_productions_unit_id_foreign` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`),
  CONSTRAINT `outlet_wip_productions_warehouse_outlet_id_foreign` FOREIGN KEY (`warehouse_outlet_id`) REFERENCES `warehouse_outlets` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
