-- Check structure of member_apps_members table
DESCRIBE member_apps_members;

-- Check column order
SELECT COLUMN_NAME, ORDINAL_POSITION, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'member_apps_members'
ORDER BY ORDINAL_POSITION;

