-- Create table payroll_generated untuk menyimpan header payroll yang sudah di-generate
CREATE TABLE IF NOT EXISTS `payroll_generated` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `outlet_id` bigint(20) UNSIGNED NOT NULL,
  `month` int(11) NOT NULL,
  `year` int(11) NOT NULL,
  `service_charge` decimal(15,2) DEFAULT 0.00,
  `status` enum('draft','generated','locked') DEFAULT 'generated',
  `created_by` bigint(20) UNSIGNED DEFAULT NULL,
  `updated_by` bigint(20) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_outlet_month_year` (`outlet_id`,`month`,`year`),
  KEY `idx_status` (`status`),
  CONSTRAINT `fk_payroll_generated_outlet` FOREIGN KEY (`outlet_id`) REFERENCES `tbl_data_outlet` (`id_outlet`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create table payroll_generated_details untuk menyimpan detail payroll per karyawan
CREATE TABLE IF NOT EXISTS `payroll_generated_details` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `payroll_generated_id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `nik` varchar(50) DEFAULT NULL,
  `nama_lengkap` varchar(255) DEFAULT NULL,
  `jabatan` varchar(255) DEFAULT NULL,
  `divisi` varchar(255) DEFAULT NULL,
  `point` decimal(10,2) DEFAULT 0.00,
  `gaji_pokok` decimal(15,2) DEFAULT 0.00,
  `tunjangan` decimal(15,2) DEFAULT 0.00,
  `total_telat` int(11) DEFAULT 0 COMMENT 'Total menit telat',
  `total_lembur` decimal(10,2) DEFAULT 0.00 COMMENT 'Total jam lembur',
  `nominal_lembur_per_jam` decimal(15,2) DEFAULT 0.00,
  `gaji_lembur` decimal(15,2) DEFAULT 0.00,
  `nominal_uang_makan` decimal(15,2) DEFAULT 0.00,
  `uang_makan` decimal(15,2) DEFAULT 0.00,
  `service_charge_by_point` decimal(15,2) DEFAULT 0.00,
  `service_charge_pro_rate` decimal(15,2) DEFAULT 0.00,
  `service_charge` decimal(15,2) DEFAULT 0.00,
  `bpjs_jkn` decimal(15,2) DEFAULT 0.00,
  `bpjs_tk` decimal(15,2) DEFAULT 0.00,
  `custom_earnings` decimal(15,2) DEFAULT 0.00,
  `custom_deductions` decimal(15,2) DEFAULT 0.00,
  `gaji_per_menit` decimal(15,2) DEFAULT 0.00,
  `potongan_telat` decimal(15,2) DEFAULT 0.00,
  `total_gaji` decimal(15,2) DEFAULT 0.00,
  `hari_kerja` int(11) DEFAULT 0,
  `periode` varchar(100) DEFAULT NULL COMMENT 'Format: dd/mm/yyyy - dd/mm/yyyy',
  `custom_items` longtext DEFAULT NULL COMMENT 'JSON custom items',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_payroll_generated_id` (`payroll_generated_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_outlet_user` (`payroll_generated_id`,`user_id`),
  CONSTRAINT `fk_payroll_details_generated` FOREIGN KEY (`payroll_generated_id`) REFERENCES `payroll_generated` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_payroll_details_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
