-- Tabel untuk menyimpan data correction yang perlu approval
CREATE TABLE `schedule_attendance_correction_approvals` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `type` enum('schedule','attendance') NOT NULL,
  `record_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `outlet_id` bigint(20) unsigned NOT NULL,
  `division_id` bigint(20) unsigned NOT NULL,
  `tanggal` date NOT NULL,
  `old_value` text,
  `new_value` text,
  `reason` text NOT NULL,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `requested_by` bigint(20) unsigned NOT NULL,
  `approved_by` bigint(20) unsigned NULL,
  `approved_at` timestamp NULL,
  `rejection_reason` text NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_type_record` (`type`, `record_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_requested_by` (`requested_by`),
  KEY `idx_approved_by` (`approved_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
