-- Create table for Stock Opname Adjustments (History of processed adjustments)
CREATE TABLE IF NOT EXISTS `outlet_stock_opname_adjustments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `stock_opname_id` bigint(20) unsigned NOT NULL COMMENT 'Reference to outlet_stock_opnames',
  `stock_opname_item_id` bigint(20) unsigned NOT NULL COMMENT 'Reference to outlet_stock_opname_items',
  `inventory_item_id` bigint(20) unsigned NOT NULL COMMENT 'Reference to outlet_food_inventory_items',
  `outlet_id` int(11) NOT NULL,
  `warehouse_outlet_id` int(11) DEFAULT NULL,
  `qty_diff_small` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT 'Selisih qty small (physical - system)',
  `qty_diff_medium` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT 'Selisih qty medium',
  `qty_diff_large` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT 'Selisih qty large',
  `reason` text DEFAULT NULL COMMENT 'Alasan selisih',
  `mac_before` decimal(15,4) DEFAULT NULL COMMENT 'MAC sebelum adjustment',
  `mac_after` decimal(15,4) DEFAULT NULL COMMENT 'MAC setelah adjustment',
  `value_adjustment` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT 'Nilai adjustment (qty_diff * MAC)',
  `processed_at` timestamp NULL DEFAULT NULL COMMENT 'Waktu adjustment di-process',
  `processed_by` bigint(20) unsigned DEFAULT NULL COMMENT 'User yang memproses adjustment',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_stock_opname_id` (`stock_opname_id`),
  KEY `idx_stock_opname_item_id` (`stock_opname_item_id`),
  KEY `idx_inventory_item_id` (`inventory_item_id`),
  KEY `idx_outlet_warehouse` (`outlet_id`, `warehouse_outlet_id`),
  KEY `idx_processed_at` (`processed_at`),
  KEY `idx_processed_by` (`processed_by`),
  CONSTRAINT `fk_opname_adj_opname` FOREIGN KEY (`stock_opname_id`) REFERENCES `outlet_stock_opnames` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_opname_adj_item` FOREIGN KEY (`stock_opname_item_id`) REFERENCES `outlet_stock_opname_items` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_opname_adj_inventory` FOREIGN KEY (`inventory_item_id`) REFERENCES `outlet_food_inventory_items` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_opname_adj_processed_by` FOREIGN KEY (`processed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Table untuk menyimpan history adjustment stock opname yang sudah di-process';

