CREATE TABLE `locked_budget_food_categories` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` bigint(20) UNSIGNED NOT NULL,
  `sub_category_id` bigint(20) UNSIGNED NOT NULL,
  `outlet_id` bigint(20) UNSIGNED NOT NULL,
  `budget` decimal(15,2) NOT NULL DEFAULT 0.00,
  `created_by` bigint(20) UNSIGNED DEFAULT NULL,
  `updated_by` bigint(20) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `locked_budget_food_categories_category_sub_outlet_unique` (`category_id`, `sub_category_id`, `outlet_id`),
  KEY `locked_budget_food_categories_category_id_foreign` (`category_id`),
  KEY `locked_budget_food_categories_sub_category_id_foreign` (`sub_category_id`),
  KEY `locked_budget_food_categories_outlet_id_foreign` (`outlet_id`),
  KEY `locked_budget_food_categories_created_by_foreign` (`created_by`),
  KEY `locked_budget_food_categories_updated_by_foreign` (`updated_by`),
  CONSTRAINT `locked_budget_food_categories_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE,
  CONSTRAINT `locked_budget_food_categories_sub_category_id_foreign` FOREIGN KEY (`sub_category_id`) REFERENCES `sub_categories` (`id`) ON DELETE CASCADE,
  CONSTRAINT `locked_budget_food_categories_outlet_id_foreign` FOREIGN KEY (`outlet_id`) REFERENCES `tbl_data_outlet` (`id_outlet`) ON DELETE CASCADE,
  CONSTRAINT `locked_budget_food_categories_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `locked_budget_food_categories_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
