-- Insert Areas Data
-- Kode area otomatis dimulai dari OPS058
-- Last kode area: OPS057

INSERT INTO areas (nama_area, kode_area, departemen_id, deskripsi, status, created_at, updated_at) VALUES
('Back Area (Steward)', 'OPS058', 1, 'Area untuk steward dan back area operations', 'A', NOW(), NOW()),
('Pastry Show Case', 'OPS059', 1, 'Area untuk pastry display dan show case', 'A', NOW(), NOW()),
('AC, Lighting (Bar Area)', 'OPS060', 1, 'Area untuk AC dan lighting di bar area', 'A', NOW(), NOW()),
('Bar Counter Set Up (Include Bar Supplies & Utensil)', 'OPS061', 1, 'Area untuk bar counter setup dan supplies', 'A', NOW(), NOW()),
('Coffee Machine & Grinder', 'OPS062', 1, 'Area untuk coffee machine dan grinder', 'A', NOW(), NOW()),
('Blender', 'OPS063', 1, 'Area untuk blender operations', 'A', NOW(), NOW()),
('Under Counter Chiller', 'OPS064', 1, 'Area untuk under counter chiller', 'A', NOW(), NOW()),
('Standing Show Case Chiller', 'OPS065', 1, 'Area untuk standing show case chiller', 'A', NOW(), NOW()),
('Chest Freezer', 'OPS066', 1, 'Area untuk chest freezer', 'A', NOW(), NOW()),
('Microwave', 'OPS067', 1, 'Area untuk microwave operations', 'A', NOW(), NOW()),
('Oven', 'OPS068', 1, 'Area untuk oven operations', 'A', NOW(), NOW()),
('Dehydrator', 'OPS069', 1, 'Area untuk dehydrator operations', 'A', NOW(), NOW()),
('Boiler Water', 'OPS070', 1, 'Area untuk boiler water system', 'A', NOW(), NOW()),
('Kamjov / Water Dispenser', 'OPS071', 1, 'Area untuk kamjov dan water dispenser', 'A', NOW(), NOW()),
('Sink & Water Supply', 'OPS072', 1, 'Area untuk sink dan water supply', 'A', NOW(), NOW()),
('Ice Bin', 'OPS073', 1, 'Area untuk ice bin operations', 'A', NOW(), NOW()),
('Igloo Ice Box', 'OPS074', 1, 'Area untuk igloo ice box', 'A', NOW(), NOW()),
('Floor, Window, Ceiling', 'OPS075', 1, 'Area untuk floor, window, dan ceiling maintenance', 'A', NOW(), NOW()),
('CCTV (Bar Area)', 'OPS076', 1, 'Area untuk CCTV di bar area', 'A', NOW(), NOW()),
('CO Printer', 'OPS077', 1, 'Area untuk CO printer operations', 'A', NOW(), NOW()),
('Commodity Preparation', 'OPS078', 1, 'Area untuk commodity preparation', 'A', NOW(), NOW()),
('FIFO / FEFO Check', 'OPS079', 1, 'Area untuk FIFO/FEFO check operations', 'A', NOW(), NOW()),
('Commodity Labeling', 'OPS080', 1, 'Area untuk commodity labeling', 'A', NOW(), NOW()),
('Employee Locker', 'OPS081', 1, 'Area untuk employee locker', 'A', NOW(), NOW()),
('Garbage Room Area', 'OPS082', 1, 'Area untuk garbage room operations', 'A', NOW(), NOW()),
('Storage Area', 'OPS083', 1, 'Area untuk storage operations', 'A', NOW(), NOW()),
('FB Office', 'OPS084', 1, 'Area untuk FB office operations', 'A', NOW(), NOW()),
('IPAL & Main Grease Trap', 'OPS085', 1, 'Area untuk IPAL dan main grease trap', 'A', NOW(), NOW()),
('Dishwashing Machine', 'OPS086', 1, 'Area untuk dishwashing machine operations', 'A', NOW(), NOW()),
('Employee Grooming', 'OPS087', 1, 'Area untuk employee grooming', 'A', NOW(), NOW());
