-- Insert data area untuk departemen_id = 1
-- Kode area akan auto generate berdasarkan nama area dan departemen

INSERT INTO `areas` (`nama_area`, `kode_area`, `departemen_id`, `deskripsi`, `status`, `created_at`, `updated_at`) VALUES
('Parking Area', 'PARKAR', 1, 'Area parkir kendaraan', 'A', NOW(), NOW()),
('Neon Sign / Loly Pop', 'NEONSI', 1, 'Area neon sign dan loly pop', 'A', NOW(), NOW()),
('Security Area', 'SECURI', 1, 'Area keamanan', 'A', NOW(), NOW()),
('Guest Waiting Area', 'GUESTW', 1, 'Area tunggu tamu', 'A', NOW(), NOW()),
('Greeter Area', 'GREETE', 1, 'Area penyambut tamu', 'A', NOW(), NOW()),
('Cashier Area', 'CASHIE', 1, 'Area kasir', 'A', NOW(), NOW()),
('Petty Cash', 'PETTYC', 1, 'Area petty cash', 'A', NOW(), NOW()),
('Pastry Show Case', 'PASTRY', 1, 'Area pastry show case', 'A', NOW(), NOW()),
('Dine-in Area & VIP Room', 'DINEIN', 1, 'Area makan dan ruang VIP', 'A', NOW(), NOW()),
('AC, Air Curtain, Lighting & Sound System', 'ACLIGH', 1, 'Sistem AC, air curtain, lighting dan sound', 'A', NOW(), NOW()),
('Table & Chair/Sofa Set Up', 'TABLES', 1, 'Set up meja dan kursi/sofa', 'A', NOW(), NOW()),
('CCTV', 'CCTV', 1, 'Sistem CCTV', 'A', NOW(), NOW()),
('Wifi Connection', 'WIFICO', 1, 'Koneksi WiFi', 'A', NOW(), NOW()),
('POS', 'POS', 1, 'Point of Sale system', 'A', NOW(), NOW()),
('CO Printer', 'COPRIN', 1, 'Printer CO', 'A', NOW(), NOW()),
('Side Station Set Up', 'SIDEST', 1, 'Set up side station', 'A', NOW(), NOW()),
('Equipment Set Up & Preparation (Condiments, Guest Supplies. etc)', 'EQUIPS', 1, 'Set up equipment dan persiapan (bumbu, perlengkapan tamu, dll)', 'A', NOW(), NOW()),
('Toilet/Washtafel', 'TOILET', 1, 'Area toilet dan washtafel', 'A', NOW(), NOW()),
('Sanitation & Hygiene', 'SANITA', 1, 'Sanitasi dan kebersihan', 'A', NOW(), NOW()),
('Mushola', 'MUSHOL', 1, 'Area mushola', 'A', NOW(), NOW()),
('Garden/Plantation', 'GARDEN', 1, 'Area taman dan tanaman', 'A', NOW(), NOW()),
('Employee Locker', 'EMPLOC', 1, 'Loker karyawan', 'A', NOW(), NOW()),
('Garbage Room Area', 'GARBAG', 1, 'Area ruang sampah', 'A', NOW(), NOW()),
('Janitor Area', 'JANITO', 1, 'Area janitor', 'A', NOW(), NOW()),
('Back Area (Steward)', 'BACKAR', 1, 'Area belakang (steward)', 'A', NOW(), NOW()),
('Storage Area', 'STORAG', 1, 'Area penyimpanan', 'A', NOW(), NOW()),
('FB Office', 'FBOFFI', 1, 'Kantor FB', 'A', NOW(), NOW()),
('IPAL & Main Grease Trap', 'IPALMA', 1, 'IPAL dan main grease trap', 'A', NOW(), NOW()),
('Media Promo (TV,Tend Card, Banner,Baligho, dll)', 'MEDIAP', 1, 'Media promosi (TV, tend card, banner, baligho, dll)', 'A', NOW(), NOW()),
('Employee Grooming (Service & Security)', 'EMPLGR', 1, 'Grooming karyawan (service & security)', 'A', NOW(), NOW());
