-- Coaching table structure
CREATE TABLE `coachings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `employee_id` bigint(20) unsigned NOT NULL,
  `supervisor_id` bigint(20) unsigned NOT NULL,
  `coaching_date` date NOT NULL,
  `violation_date` date DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `violation_details` text DEFAULT NULL,
  `disciplinary_actions` json DEFAULT NULL,
  `supervisor_comments` text DEFAULT NULL,
  `employee_response` text DEFAULT NULL,
  `supervisor_signature` varchar(255) DEFAULT NULL,
  `employee_signature` varchar(255) DEFAULT NULL,
  `status` enum('draft','completed') DEFAULT 'draft',
  `created_by` bigint(20) unsigned NOT NULL,
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `coachings_employee_id_foreign` (`employee_id`),
  KEY `coachings_supervisor_id_foreign` (`supervisor_id`),
  KEY `coachings_created_by_foreign` (`created_by`),
  KEY `coachings_updated_by_foreign` (`updated_by`),
  CONSTRAINT `coachings_employee_id_foreign` FOREIGN KEY (`employee_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `coachings_supervisor_id_foreign` FOREIGN KEY (`supervisor_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `coachings_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `coachings_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
