-- Create table for Member Apps Vouchers
CREATE TABLE IF NOT EXISTS `member_apps_vouchers` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text NULL DEFAULT NULL,
  `voucher_type` enum('discount-percentage', 'discount-fixed', 'free-item', 'cashback') NOT NULL,
  `discount_percentage` decimal(5,2) NULL DEFAULT NULL COMMENT 'Percentage discount (e.g., 10.00 for 10%)',
  `discount_amount` decimal(15,2) NULL DEFAULT NULL COMMENT 'Fixed discount amount',
  `min_purchase` decimal(15,2) NULL DEFAULT NULL COMMENT 'Minimum purchase required',
  `max_discount` decimal(15,2) NULL DEFAULT NULL COMMENT 'Maximum discount amount (for percentage)',
  `free_item_id` bigint(20) UNSIGNED NULL DEFAULT NULL COMMENT 'If voucher_type = free-item',
  `free_item_name` varchar(255) NULL DEFAULT NULL,
  `cashback_amount` decimal(15,2) NULL DEFAULT NULL COMMENT 'If voucher_type = cashback',
  `cashback_percentage` decimal(5,2) NULL DEFAULT NULL COMMENT 'If voucher_type = cashback',
  `valid_from` date NOT NULL,
  `valid_until` date NOT NULL,
  `usage_limit` int(11) NULL DEFAULT NULL COMMENT 'Max usage per member (NULL = unlimited)',
  `total_quantity` int(11) NULL DEFAULT NULL COMMENT 'Total voucher quantity (NULL = unlimited)',
  `applicable_channels` json NULL DEFAULT NULL COMMENT 'Array: ["dine-in", "take-away", "delivery-restaurant"]',
  `applicable_days` json NULL DEFAULT NULL COMMENT 'Array: ["monday", "tuesday", etc]',
  `applicable_time_start` time NULL DEFAULT NULL,
  `applicable_time_end` time NULL DEFAULT NULL,
  `exclude_items` json NULL DEFAULT NULL COMMENT 'Array of item IDs to exclude',
  `exclude_categories` json NULL DEFAULT NULL COMMENT 'Array of category IDs to exclude',
  `image` varchar(255) NULL DEFAULT NULL COMMENT 'Voucher image/banner',
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_by` bigint(20) UNSIGNED NULL DEFAULT NULL COMMENT 'User ID who created',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_voucher_type` (`voucher_type`),
  KEY `idx_valid_from` (`valid_from`),
  KEY `idx_valid_until` (`valid_until`),
  KEY `idx_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create table for Voucher Distribution (Who gets the voucher)
CREATE TABLE IF NOT EXISTS `member_apps_voucher_distributions` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `voucher_id` bigint(20) UNSIGNED NOT NULL,
  `distribution_type` enum('all', 'specific', 'filter') NOT NULL COMMENT 'all=all members, specific=specific member IDs, filter=by criteria',
  `member_ids` json NULL DEFAULT NULL COMMENT 'Array of member IDs if distribution_type = specific',
  `filter_criteria` json NULL DEFAULT NULL COMMENT 'Filter criteria if distribution_type = filter',
  `total_distributed` int(11) NOT NULL DEFAULT 0 COMMENT 'Total vouchers distributed',
  `total_used` int(11) NOT NULL DEFAULT 0 COMMENT 'Total vouchers used',
  `distributed_at` timestamp NOT NULL,
  `created_by` bigint(20) UNSIGNED NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_voucher_id` (`voucher_id`),
  KEY `idx_distribution_type` (`distribution_type`),
  KEY `idx_distributed_at` (`distributed_at`),
  CONSTRAINT `fk_voucher_distribution_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `member_apps_vouchers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create table for Member Vouchers (Individual voucher assignment)
CREATE TABLE IF NOT EXISTS `member_apps_member_vouchers` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `voucher_id` bigint(20) UNSIGNED NOT NULL,
  `voucher_distribution_id` bigint(20) UNSIGNED NULL DEFAULT NULL COMMENT 'Reference to distribution batch',
  `member_id` bigint(20) UNSIGNED NOT NULL,
  `voucher_code` varchar(50) NOT NULL UNIQUE COMMENT 'Unique voucher code',
  `status` enum('active', 'used', 'expired', 'cancelled') NOT NULL DEFAULT 'active',
  `used_at` timestamp NULL DEFAULT NULL,
  `used_in_transaction_id` varchar(255) NULL DEFAULT NULL COMMENT 'Reference to transaction where voucher was used',
  `expires_at` date NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_voucher_code` (`voucher_code`),
  KEY `idx_voucher_id` (`voucher_id`),
  KEY `idx_voucher_distribution_id` (`voucher_distribution_id`),
  KEY `idx_member_id` (`member_id`),
  KEY `idx_status` (`status`),
  KEY `idx_expires_at` (`expires_at`),
  KEY `idx_voucher_code` (`voucher_code`),
  CONSTRAINT `fk_member_voucher_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `member_apps_vouchers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_member_voucher_distribution` FOREIGN KEY (`voucher_distribution_id`) REFERENCES `member_apps_voucher_distributions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_member_voucher_member` FOREIGN KEY (`member_id`) REFERENCES `member_apps_members` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

