<?php

declare(strict_types=1);

return [
    'Artisan Tea Ceylon Green Tea',
    'Artisan Tea Ginger & Mint',
    'Bawang Goreng',
    'Beef Black Angus Striploin 250gr',
    'Beras Jepang',
    'Beras Lokal',
    'Beras Pandan Wangi',
    'Black Pepper',
    'Black Truffle Paste',
    'Buah Lychee Can',
    'Buah Peach Can',
    'Butter Salted',
    'Chicken Powder',
    'Chilli Flake',
    'Chilli Sachet',
    'Chocolate Compound',
    'Coca Cola Can',
    'Coca Cola Zero Can',
    'Cokelat Powder',
    'Cream Soup Powder',
    'Creamer',
    'Cup 12 Logo SH',
    'Donut Dusting',
    'Equil',
    'Equil Sparkling',
    'Fryall',
    'Garam Refina',
    'Gas Whipped',
    'Gerkin',
    'Guacamole',
    'Gula Pasir',
    'Gula Putih Sachet SH',
    'House Blend',
    'Kacang Arab',
    'Kacang Tanah',
    'Kecap Asin',
    'Kecap Asin Angsa',
    'Kerupuk Emping',
    'Madu',
    'Marjan Lychee',
    'Marjan Strawberry',
    'Marjan Vanilla',
    'Mayonaise',
    'Merica Halus',
    'Milk Evaporate',
    'Minyak Goreng',
    'Minyak Klentik',
    'Nestea Powder',
    'Nutmeg',
    'Olive Oil 500Mili liter',
    'Onion',
    'Oregano',
    'Oyster Sauce',
    'Pasta Fettucine',
    'Pasta Macaroni',
    'Pasta Spaghetti',
    'Plastik Roll Buah 30x45',
    'Plastik Wrap',
    'SKM Putih',
    'Salad Bowl',
    'Salad Oil',
    'Santan',
    'Sauce Chilli Botol',
    'Sauce Chocolate',
    'Sauce Cup',
    'Sauce Cup Dessert',
    'Sea Salt Baby Pyramid',
    'Sedotan',
    'Skewer Burger',
    'Skewer Rotan Simpul',
    'Soda Water',
    'Spinach Bowl',
    'Sticker Botol Aren',
    'Sunquick',
    'Syrup Green Apple',
    'Syrup Gula Aren',
    'Syrup Hazelnut',
    'Syrup Kawista',
    'Syrup Mint',
    'Syrup Peach',
    'Teh Celup',
    'Tepung Beras',
    'Tepung Easy Mix',
    'Tepung Roti Kasar',
    'Tepung Terigu',
    'Thyme',
    'Tomato Peeled',
    'Truffle Oil',
    'Vetcin Powder',
    'Vinegar Dixi',
    'Dishwash',
    'General Cleaner',
    'Greezaway',
    'Hairnet',
    'Hand Soap',
    'Hands Glove Rubber',
    'Masker 3 Ply',
    'HVS 1 Ply 75x65',
    'Label Preparation Roll',
];
