<?php

return [
    'Beras Lokal',
    'Beras Pandan Wangi',
    'Black Pepper',
    'Buah Lychee Can',
    'Buah Peach Can',
    'Cheese Powder',
    'Chicken Powder',
    'Chilli Flake',
    'Chocolate Compound',
    'Coca Cola Can',
    'Coca Cola Zero Can',
    'Cokelat Powder',
    'Cream Soup Powder',
    'Fryall',
    'Garam Kapal',
    'Garam Refina',
    'Gas Whipped',
    'Gerkin',
    'Guacamole',
    'Gula Pasir',
    'Gula Putih Sachet SH',
    'Kecap Asin Angsa',
    'Kecap Manis',
    'Kerupuk Emping',
    'Madu',
    'Marjan Lychee',
    'Marjan Strawberry',
    'Marjan Vanilla',
    'Mayonaise',
    'Milk Evaporate',
    'Minyak Klentik',
    'Nestea Powder',
    'Olive Oil 500Mili liter',
    'Oyster Sauce',
    'Pasta Fettucine',
    'Pasta Lasagna',
    'Pasta Spaghetti',
    'Plastik Roll Buah 30x45',
    'Plastik Wrap',
    'Salad Bowl',
    'Sauce Chilli Botol',
    'Sauce Cup',
    'Sauce Cup Dessert',
    'Sauce Tomat Botol',
    'Skewer Rotan Simpul',
    'Soda Water',
    'Soun',
    'Sunquick',
    'Syrup Gula Aren',
    'Syrup Kawista',
    'Syrup Mint',
    'Tabasco Sauce',
    'Teh Celup',
    'Tepung Easy Mix',
    'Tepung Roti Kasar',
    'Thyme',
    'Tissue Dinner',
    'Tissue Pop Up',
    'Tissue Roll',
    'Tissue Towel',
    'Truffle Oil',
    'Dishwash',
    'General Cleaner',
    'Hairnet',
    'Hands Glove Rubber',
    'Masker 3 Ply',
    'HVS 1 Ply 75x65',
    'Label Preparation Roll',
    'Thermal Roll Steak house',
];
